[package]
name = "dhall"
version = "0.1.0"
authors = ["NanoTech <nanotech@nanotechcorp.net>", "Nadrieril <nadrieril@users.noreply.github.com>"]
license = "BSD-2-Clause"
edition = "2018"
build = "build.rs"

[dependencies]
bytecount = "0.5.1"
itertools = "0.8.0"
term-painter = "0.2.3"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.10.2"
improved_slice_patterns = { version = "2.0.0", path = "../improved_slice_patterns" }
dhall_syntax = { path = "../dhall_syntax" }
dhall_proc_macros = { path = "../dhall_proc_macros" }

[dev-dependencies]
pretty_assertions = "0.6.1"

[build-dependencies]
walkdir = "2"

